### ISSUE TITLE
Project and Sample Size estimates are incorrect

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-portal#119]
### Context

On the portal it says the projects and samples are around ~1.1 MB which is incorrect. 

### Problem or idea

Figure out where the calculation is going wrong and present correct size estimates.

**Comment by kurtwheeler** [comment]
This was fixed by https://github.com/AlexsLemonade/scpca-portal/pull/107, which has finally been deployed reloaded.
