### ISSUE TITLE
Add alarm and throttling for API

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/scpca-portal#127]
### Context

The API went down for a few days without us knowing because we got DOSed.

### Problem or idea

We should add an alarm so we know next time, but also add throttling to prevent this from happening at all.

### Solution or next step

Add a cloudwatch alarm. Set up an ACL WAF on the load balancer based on IP.

**Comment by davidsmejia** [comment]
Closing and opening https://github.com/AlexsLemonade/scpca-portal/issues/321
