### ISSUE TITLE
Look into Windows table experience

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-portal#135]
### Context

Observed during evals

### Problem or idea

On windows, mouse/trackpad does not support horizontal scrolling. The scrollbar is only visible at the bottom of the page, so user on smaller screen resolutions will need to scroll up and down to move horizontally using the scrollbar. It is extremely frustrating to browse through the samples table on Windows. 

At this point, I'm not sure how much of it is native and how much of it we can control. We will need to look into that before we can outline a solution. 

We should also check % of windows users we have too. (not for ScPCA but for refine bio to get a super rough sense) 

### Solution or next step

@davidsmejia and I can talk it out and figure out alternatives for Windows users.

**Comment by dvenprasad** [comment]
![2022-01-14 10 59 36](https://user-images.githubusercontent.com/15315514/149546219-5408106e-e700-4887-a9a3-3734db0951fd.gif)

**Comment by davidsmejia** [comment]
Make 5 rows shown by default, add dropdown to change, save selection in local storage
