### ISSUE TITLE
Provide UMAPs along with QC in the downloads

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-portal#136]
_Please label your issue with a label to specify its priority: breaking, high, medium, or low._

### Context

Came up during evals. Users wanted to as something visual to quickly get a look at what's happening in the file

### Problem or idea

Would be nice to provide a UMAP (someone also mentioned a tSNE-plot).
We could see if it is also worth providing other basic visualizations "like 10x does".

**Comment by jaclyn-taroni** [comment]
There are now UMAPs in the QC reports.
