### ISSUE TITLE
The second checkbox on the Download Project modal is (probably) wrong

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-portal#145]
_Please label your issue with a label to specify its priority: breaking, high, medium, or low._

### Context

I went to download a project and was confused by language on the download project model.

### Problem or idea

The second checkbox in the modal says `I would like to receive occasional updates from the Privacy Policy` where `Privacy Policy` links to https://www.ccdatalab.org/

<img width="1622" alt="Screen Shot 2022-02-24 at 1 30 26 PM" src="https://user-images.githubusercontent.com/19534205/155585685-44ccefb6-e4a5-427b-a6ae-22ddd72a0191.png">

### Solution or next step

Change `Privacy Policy` to `Childhood Cancer Data Lab` - tagging @davidsmejia. I've labeled this as medium, but we do probably want to fix this before we announce.

**Comment by davidsmejia** [comment]
closed with #146
