### ISSUE TITLE
ScPCA Analytics Strategy Doc

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-portal#20]
@jaclyn-taroni commented on [Mon Aug 09 2021](https://github.com/AlexsLemonade/AdminItems/issues/370)

_Issue created from #369_

Current plan is to:

- Have @davidsmejia outline the goals and @dvenprasad write up what information it will be useful to collect next sprint, so that's in place before lo-fis are in full swing 
- Fill this in more (e.g., what to implement & how) once we have a few wireframes

**Comment by jaclyn-taroni** [comment]
Outcome of a meeting late last week: first step is to have Deepa draft up goals

**Comment by dvenprasad** [comment]
Done, it lives in the CCDL shared drive in the folder labeled `ScPCA`. It's living doc and more will be added as we design the modules.
