### ISSUE TITLE
ScPCA Downloaders List not getting updated

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-portal#224]
### Context

We keep a list on hubspot called "ScPCA Downloaders" to collect emails and send them a survey. The list is not getting updated. There's only a test person on the list. 

### Problem or idea

People should get added to that list when they provide us with their email when they download (regardless of whether they check the "Want to receive updates" box) 

### Solution or next step

 Tagging @nozomione @davidsmejia  for next steps

**Comment by nozomione** [comment]
Related issue: https://github.com/AlexsLemonade/scpca-portal/issues/148

**Comment by nozomione** [comment]
An environmental variable for the form will be added in our next deployment and that should resolve the issue. 
No code change required, thank you Deepa!
