### ISSUE TITLE
Add favicon and ensure page titles render on broswer tabs

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-portal#225]
### Context

<img width="243" alt="Screen Shot 2022-05-23 at 9 58 00 AM" src="https://user-images.githubusercontent.com/15315514/169836224-4e641ef5-ace6-485b-b15e-511ca03700e5.png">

### Problem or idea

Add a favicon (the blue lemon from resources portal) and show human readable and relevant page titles 
For example: The below image should say : About- ScPCA Portal 

<img width="314" alt="Screen Shot 2022-05-23 at 9 58 06 AM" src="https://user-images.githubusercontent.com/15315514/169836841-b81a2119-fdf2-46da-b805-8f6c403d0a2b.png">

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by nozomione** [comment]
Related issue: https://github.com/AlexsLemonade/scpca-portal/pull/179
**Note:** The favicon has been added to the codebase. Once we deploy the change to Production, it will load correctly, thanks!
