### ISSUE TITLE
Consider splitting load data script logic

### ISSUE THREAD

**Issue by arkid15r** [AlexsLemonade/scpca-portal#264]
> Maybe we would be better served by pulling some of the load data logic and properties into another module or two. 
> 
>   - As some methods only make sense when the files are locally available. That is to say if you accessed `project.output_multiplexed_computed_file_name`, I don't believe we should expect that to exist outside of the time the file is being generated as a property of the project. I think we should give it some thought at least.
> 
>   - For the functions that generate computed files and their zips. It looks like some of the overall patterns are very similar and we could probably reduce some repetition there. 

_Originally posted by @davidsmejia in https://github.com/AlexsLemonade/scpca-portal/pull/246#pullrequestreview-1025529950_

**Comment by davidsmejia** [comment]
closing in favor of #634
