### ISSUE TITLE
1 or more samples will be made available soon.

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/scpca-portal#287]
### Context

One of the samples has no single cell data but we include the bulk data in the project download. We won't allow this sample to be downloaded individually but we have this mechanism in place that compares the known sample count (all samples) against the downloadable samples. 

![Screen Shot 2022-07-19 at 1 52 16 PM](https://user-images.githubusercontent.com/1075609/179816773-0a8584e1-fc54-4ca4-8a42-2156f7c3dc53.png)

### Problem or idea

I'm thinking we should update the downloadable sample count to include the bulk sample so this message goes away. Or we should include another number not `samples_count` on the project that shows downloadable samples that we expect to be available.

### Solution or next step

Tagging @ark @dvenprasad for ideas and comments

**Comment by dvenprasad** [comment]
If we include bulk samples in sample count, would that double count in cases where both SC and bulk are available for a sample?

**Comment by davidsmejia** [comment]
@dvenprasad I think after giving this some thought the best option would be adding `has_single_cell_data` to the project and sample models. Then updating the `downloadable_sample_count` to any sample where `has_single_cell_data` is `True` and has a `computed_file.type` that is `sample_zip`. I'm not sure this will cover all future cases but this will get us out of the current bind.

**Comment by davidsmejia** [comment]
Closing with #288 #289
