### ISSUE TITLE
ScPCA Development Timeline

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-portal#3]
@davidsmejia commented on [Thu Jul 29 2021](https://github.com/AlexsLemonade/AdminItems/issues/369)

Here are the milestones and timeline for the ScPCA portal.

NB:
* All milestones are listed with the sprint start date for when that work will be completed.
* The dates might get shifted but the rational for the start date was to wait for Will to leave before Kurt kicks off the back end.
* Most of the FE is generic but we aren't 100% sure about what the FE will look like.
* ~Expect this to be updated after the meeting on Monday when we have a better sense of MVP functionality~

### Meeting updates 8/2/21:
  * projects will be pre-zipped and you will download individual `projects`
  * projects will be broken down by cancer type
  * no elastic search or free text search but we will use DRF filtering on `projects` so filters can apply to `projects` or `samples` they contain
  * updated the timeline below to account for these changes

## Misc Tasks

* [x] Data model
* [x] [List of Pages/Views for the frontend](https://github.com/AlexsLemonade/AdminItems/issues/369#issuecomment-898507852)
* [x] Set up Sentry and setup Sentry Environments
* [x] #20
* [x] https://github.com/AlexsLemonade/scpca-portal/issues/65

# Development Milestones (Updated 8/3/21)

8/2/21 - 10/12/21

## Pre-Kickoff 8/2/21

- **Design**
  - [x] #19 
  - [x] [Rough IA](https://github.com/AlexsLemonade/AdminItems/issues/369#issuecomment-898507852)
  - [x] #1

## Kickoff 8/17/21
   - **Design**
      - [x] #1 
         - [x] Low-fi + High-fi Reviews
         - [x] Discuss tracking metrics

  * **Backend**
    * [x] #11 
    * [x] #12 
    * [x] #13 
    * [x] #14 
    * [x] #15 
    * [x] #17 
    * [x] #18 

  * **Frontend**
    * [x] #4
    * [x] #5
    * [x] #6
    * [x] #7
    * [x] #8
    * [x] #9
    * [x] #10

## Bulk of application 8/31/21
   - **Design**
      - [x] #42
          - [x] Low-fi
          - [x] High-fi 
           - [x] Discuss tracking metrics

  * Backend
    * [x] Bug Fixes

  * Frontend
    * [x] #39
    * [x] #40
    * [x] #41

## Getting data and staging deploy 9/14/21
  - **Design**
    - [x] #57
         - [x] Low-fi
         - [x] High-fi 
         - [x] Discuss tracking metrics (if applicable)
    - [x] Empty States

  - Backend
    * [x] Bug Fixes

  - Frontend
    * [x] #58 
    * [x] #59
    * ~Add Browse By Tumor Type Page with Filtering~

## Soft Launch + Support 9/28/21

  - **Design**
    - [x] Dogfood portal and identify issues

  - Backend
    - [x] Bug Fixes / Late Changes

  - Frontend
    - [x] Add Samples Listing Components
    - [x] Add Download Modal
    - [x] #77

## Final Launch 10/12/21
  * Backend
    * [x] Bug Fixes
    * [x] Production Deploy

  * Frontend
    * [x] #84
    * [x] Add Documentation Links
    * [x] Bug Fixes
    * [x] Production Deploy

# Post Project
* [x] #95
* [x] ScPCA Postmortem

---

@dvenprasad commented on [Fri Aug 13 2021](https://github.com/AlexsLemonade/AdminItems/issues/369#issuecomment-898507852)

**Rough Sitemap/IA**
- Home - Links to Browse by tumor type, Browse by Project, Docs.
- Browse by Tumor Type
- Browse by Project
- Project Page
  - Project Details
  - Sample Details
  - Download Modal - T&C and collect email/ "Hey the download is starting." Here's a summary of the files (I can be persuaded to consider a page instead) 
 - Docs

**Comment by kurtwheeler** [comment]
https://github.com/AlexsLemonade/scpca-portal/issues/33 and https://github.com/AlexsLemonade/scpca-portal/issues/32 have also come up.

**Comment by davidsmejia** [comment]
Note: waiting on lofis for filtering options for the "search" pages
