### ISSUE TITLE
New feature: Allow for sample metadata exports

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-portal#312]
### Context

I am proposing new features to download sample metadata. I am proposing this because it is a common feature in other databases that has proven (for me!) a very useful way to get an overall sense of the full data a given resource offers, _without_ having to download the large datasets themselves.

### Problem or idea

I recommend two interrelated features:
- The ability to download all sample metadata for a given project in one click. This is complementary to the current ability to download all project files in one click. It would be great to always pair a "download project metadata" button next to any "download project" buttons.
- The ability to download all sample metadata _combined across all projects_ (more or less `cat` all the sample metadata files) in one click. It would be great to see this on the overall "browse" page, and maybe also on the landing page somewhere.

**Comment by sjspielman** [comment]
Note that I'm torn between low vs. medium priority here. This is probably low in the scheme of things, but I think it would be a _significant_ improvement as more people start to browse the catalog!

**Comment by jaclyn-taroni** [comment]
I just want to point out that it might be the case that most users of the portal prefer to review metadata via the samples table that already exists. We'd have to evaluate. We are not our users.

**Comment by jaclyn-taroni** [comment]
Note that we got a request along these lines to the scpca email inbox.

**Comment by davidsmejia** [comment]
This can be closed as we now support project level metadata downloads as well as portal wide metadata downloads.
