### ISSUE TITLE
Report publications associated with projects on the frontend

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-portal#320]
_Please label your issue with a label to specify its priority: breaking, high, medium, or low._

This is something we should do as soon as we can get to it in my opinion. I thought it was tracked somewhere, but I can't find the issue.

### Context

There's at least one dataset that has a publication associated with it in the project metadata. 

### Problem or idea

We should expose this information on the frontend. Specifically, I'd expect to see it on the project details page.

**Edit on 12/11/22** We should support _multiple publications_ per project.

### Solution or next step

Tagging @dvenprasad for input

**Comment by dvenprasad** [comment]
Add 2 fields on view experiment page
DOI: 10.1016/j.devcel.2022.04.003
Citation: Patel A. G., X. Chen, X. Huang, M. R. Clay, N. Komorova, et al., 2022 The myogenesis program drives clonal selection and drug resistance in rhabdomyosarcoma. Dev Cell 57: 1226-1240.e8. https://doi.org/10.1016/j.devcel.2022.04.003

**Comment by davidsmejia** [comment]
> 

@dvenprasad should the DOI show up as a hyperlink in the citation as well? Or only from the citation field in the list?

**Comment by dvenprasad** [comment]
Yes, please hyperlink the DOI field too
