### ISSUE TITLE
Test loading data with `_processed.rds` files on staging

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-portal#327]
### Context

We're adding a new file for each single-cell and single-nuclei library that contains filtered and normalized data (`_processed.rds`).

### Problem or idea

We need to test loading data with these new files on staging. It's very possible this just works™️ and doesn't require any code changes.

### Solution or next step

@davidsmejia I'm slotting this for next sprint (it's in `On Deck` and the sprint Dec 12-23), as I expect that the science team will be ready to handoff processed data by the end of the current sprint.

**Comment by davidsmejia** [comment]
Did not work out of the box, there are some minor changes required which are captured in this ticket. https://github.com/AlexsLemonade/scpca-portal/issues/336

Closing with newly opened issue.
