### ISSUE TITLE
Support multiple contacts for a single project

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-portal#333]
### Context

There is at least one project where we need to list more than one contact person. We do not currently support that.

### Problem or idea

* `contact_email` and `contact_name` will be comma-separated in the project metadata the science team hands off. 
* The `Project` model needs to be adjusted accordingly. 
* The front end should display as many contacts as are associated with the project.

### Solution or next step

I'm going to tag @dvenprasad to weigh on the display, specifically. I will also slot this for next sprint.

**Comment by dvenprasad** [comment]
Add the second one right below the first one as a list
```
Contact Name1 <contact1@email.com>
Contact Name2 <contact2@email.com>
```
