### ISSUE TITLE
Update how projects-metadata is synced.

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/scpca-portal#340]
### Context

When we load in a specific project or sample, the projects-metadata.csv file is not re-downloaded.

Running the following command:
`sportal load-data --spcpca-project-id XXXXXX` 

Will re-sync the project's  data files but any metadata that is loaded from projects-metadata is potentially stale.

### Solution next step

Can we either add a new command ex: `sportal sync-projects-metadata` or make sure that we re-sync this file when re-loading a project or sample.

**Comment by arkid15r** [comment]
I wasn't able to reproduce the behavior for current `dev` branch:

> 11:41:58  ❯ rm api/data/input/project_metadata.csv
> 
> scpca-portal on 🌱 dev [?] via 🐍 v3.10.6
> 11:42:08 ❯ sportal load-data --scpca-project-id SCPCP000009 --reload-existing
> [+] Running 2/0
>  ⠿ Container scpca-portal-client-1    Running                                                                                                                                                                                         0.0s
>  ⠿ Container scpca-portal-postgres-1  Running                                                                                                                                                                                         0.0s
> _download: s3://scpca-portal-inputs/project_metadata.csv to data/input/project_metadata.csv_
> Purging 'Project SCPCP000009'
> Importing 'Project SCPCP000009' data
> Created 39 samples for 'Project SCPCP000009'
> 
> scpca-portal on 🌱 dev [?] via 🐍 v3.10.6 took 5m31s
> 

[Here](https://github.com/AlexsLemonade/scpca-portal/blob/dev/api/scpca_portal/management/commands/load_data.py#L122) we make sure the file is included for the update.

**Comment by davidsmejia** [comment]
Fixed with https://github.com/AlexsLemonade/scpca-portal/pull/360 - Not sure why
