### ISSUE TITLE
Multiple publications are concatenated on the frontend

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-portal#383]
_Please label your issue with a label to specify its priority: breaking, high, medium, or low._

### Context

Multiple publications are not getting parsed as expected on the frontend, both on the project details page and the search card:

![Screenshot 2023-04-12 at 12 22 27 PM](https://user-images.githubusercontent.com/19534205/231520911-dc27133c-6d87-4ad3-9a4f-5ef5f895300f.png)

![Screenshot 2023-04-12 at 12 22 13 PM](https://user-images.githubusercontent.com/19534205/231520849-66575bf6-c4a9-4485-8a3d-695865a5aa83.png)

https://github.com/AlexsLemonade/scpca-portal/issues/320 is done, but still open

### Problem or idea

The citations should be on separate lines
The DOIs can either be on separate lines or ; separated (cc: @dvenprasad )

### Solution or next step

Tagging @davidsmejia 

**Edit:** It's possible it is an issue with the project file, but I think we need to figure that out here.

**Comment by dvenprasad** [comment]
Both Publications and DOI can be displayed on separate lines.

**Comment by davidsmejia** [comment]
The parsing is fine, the elements used are not breaking by default to comply with the intended layout.
