### ISSUE TITLE
Libraries that contain CITE-seq are missing

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/scpca-portal#384]
### Context

Libraries that contain CITE-seq are missing from the portal but they are present in the hand off bucket.

### Problem or idea

We know at this time there are missing libraries from this project: https://api.scpca.alexslemonade.org/v1/projects/SCPCP000008

### Solution or next step

Investigate why these libraries are not available.

**Comment by arkid15r** [comment]
The issue was fixed with a rebuild after the corrected metadata files had been uploaded.
