### ISSUE TITLE
Remove duplicate Bulk data filter

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-portal#424]
### Context

Filtering for Bulk data is duplicated as `Bulk` and `Bulk RNA-seq` filter options.

<img width="297" alt="Screenshot 2023-08-25 at 23 25 12" src="https://github.com/AlexsLemonade/scpca-portal/assets/15315514/3e0c80eb-7348-4148-822d-f468fb329ad7">

### Problem or idea

Remove `Bulk` filter and retain `Bulk RNA-seq` filter. 

### Solution or next step

Tagging @davidsmejia for next steps

**Comment by davidsmejia** [comment]
@arkid15r could you look to see if the cause of this is due to something during the import process. It looks to me that we are creating two modalities when we should be creating one.

**Comment by arkid15r** [comment]
For some reason the extra filter option is added on the FE.
The projects metadata needs to be updated after fix is deployed as the label text has been updated on the BE.
