### ISSUE TITLE
 Display external accession on the portal

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-portal#455]
### Context

We would like to show other repositories where the data is also deposited (external accessions)

### Problem or idea
Add a field `Also deposited under` on:

- Project Card - show after Publications, values are comma separated. 
![Screenshot 2023-10-12 at 11 17 50](https://github.com/AlexsLemonade/scpca-portal/assets/15315514/0a06ffea-52d5-4c13-8993-9d520c983aff)

- Project Details Page - show after DOI, values are separated by a new line.
![Screenshot 2023-10-12 at 11 19 36](https://github.com/AlexsLemonade/scpca-portal/assets/15315514/ebafbff4-0d92-48f5-a21d-d3062a035ad3)

- If external accessions aren't available populate the field with `Not Available` on both project card and project details page. 
![Screenshot 2023-10-12 at 11 24 05](https://github.com/AlexsLemonade/scpca-portal/assets/15315514/fc130da1-b4db-4948-b589-adb1844d81ac)

### Solution or next step

Tagging @davidsmejia for next steps

**Comment by davidsmejia** [comment]
closed with #477
