### ISSUE TITLE
Update README templates to include supplemental cell type report

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-portal#457]
### Context

We will be adding a new file for each sample that will be included with downloads. This file is an additional html file that holds supplemental information about the cell types included in the `SingleCellExperiment` or `AnnData` objects (`SCPCL000000_celltype_report.html`).

### Problem or idea

The addition of the new file needs to be reflected in the `README` templates that we use when people download single-cell/ single-nuclei data. 

### Solution or next step

Add the supplemental QC report to the list of files included with each library in both the `README` for `SingleCellExperiment` and `AnnData` objects.

**Comment by jaclyn-taroni** [comment]
Closed by #558, which went into `feature/community-contributed-data`
