### ISSUE TITLE
Account for extra cell type report in downloads

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-portal#461]
### Context

We are working on adding cell type annotations to all of the samples available on the portal. As part of that, we are now providing an additional `html` file that includes supplemental information about the cell types.  One thing to note is that some cell type information is still available in the main `_qc_report.html` file, and the supplemental `html` file will contain both the cell type section of the main report and additional descriptive text and metrics.  This file will now need to be included in downloads.

### Problem or idea

Because of this, we will need to update the download structure for those modalities. This report should be included in the sample ID folder. We will be including all relevant information needed to interpret cell types within this report, so if a user opened up this report first then they would have the context that they needed. That's why I think it makes more sense to include this report at the same level as the main qc report.

These changes will affect single-cell/single-nuclei samples, CITE-seq samples, and multiplexed samples, but not spatial.

### Solution or next step

Proposed download structure for projects: 
```
project_id
├── README.md
├── bulk_metadata.tsv
├── bulk_quant.tsv
├── sample_id
│   ├── SCPCL000000_filtered.rds
│   ├── SCPCL000000_processed.rds
│   ├── SCPCL000000_qc_report.html
|   ├── SCPCL000000_celltype_report.html*
│   ├── SCPCL000000_unfiltered.rds
└── single_cell_metadata.tsv
```

Proposed download structure for samples: 
```
sample_id
├── README.md
├── SCPCL000000_filtered.rds
├── SCPCL000000_processed.rds
├── SCPCL000000_qc_report.html
├── SCPCL000000_celltype_report.html*
├── SCPCL000000_unfiltered.rds
└── single_cell_metadata.tsv
```

**Comment by jaclyn-taroni** [comment]
@davidsmejia - Since this was originally written, we've decided to skip cell typing for cell line samples. At a project level, you should only see "missing" cell type reports when `includes_cell_lines` is `TRUE`. We also indicate whether or not a sample level, but I'm not sure if that field will be passed off to you. This is probably something to discuss in `#scpca` when implementation starts.

**Comment by davidsmejia** [comment]
Closing with #623
