### ISSUE TITLE
Direct docs link towards default version in scpca-docs

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-portal#468]
### Context

We have been working on versioning the docs for ScPCA and recently updated RTD to build a new version for every tag we create. That tagged version then becomes the default version for the docs. We are using dates for tags. 

When people navigate to the docs we want them to be able to see the latest tagged version. Right now, the link takes you directly to the `latest` version, which may or may not be up to date with the tagged version. 

For some additional context, see For some additional context see, https://github.com/AlexsLemonade/scpca-docs/issues/168. 

### Problem or idea

Currently, the link to the docs from the portal takes you to https://scpca.readthedocs.io/en/latest/ which shows the `latest` version: 
<img width="864" alt="Screenshot 2023-11-01 at 4 10 07 PM" src="https://github.com/AlexsLemonade/scpca-portal/assets/54039191/c1da4bdb-14fe-4f99-994b-e43addfc9e00">

But what we want is to be taken to https://scpca.readthedocs.io/ which will show the default version that is automatically set to the most recent tag in `scpca-docs`. 

<img width="814" alt="Screenshot 2023-11-01 at 4 10 51 PM" src="https://github.com/AlexsLemonade/scpca-portal/assets/54039191/275d8e12-61ee-4970-8a55-e6a799e6b2ef">

### Solution or next step

The link that's used for navigating from the portal to the docs should be updated to be: https://scpca.readthedocs.io/

Tagging @dvenprasad and @davidsmejia for this. Let me know if there are any questions that you have!

**Comment by davidsmejia** [comment]
Closed with #476
