### ISSUE TITLE
Add README template with research or academic purposes only language

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-portal#482]
_Please label your issue with a label to specify its priority: breaking, high, medium, or low._

### Context

We will be updating the Terms of Use for the ScPCA Portal. We must mark some datasets as designated for research or academic purposes only. The README included in the download should state when this designation applies to a project and sample.

### Problem or idea

We'll create a separate README template file that includes the language that tells users a project is designated for research or academic purposes only. This will be added to the README included in a download when applicable.

### Solution or next step

Someone on the science team will:

- [ ] #483
- [ ] Update the other README templates to indicate _where_ this language should go.

**Comment by jaclyn-taroni** [comment]
Use the following as the placeholder in the other README templates:
```
{additional_terms}
```

**Comment by jaclyn-taroni** [comment]
David recommends calling this `api/scpca_portal/templates/additional_terms_research_academic_only.md`

**Comment by davidsmejia** [comment]
Closed with #547
