### ISSUE TITLE
Changes for community contributed datasets and additional filters

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-portal#485]
### Context
This is a dev hand-off ticket

### Problem or idea

The changes and annotated high-fis for community contributed datasets and additional filters can be found in this [figjam file](https://www.figma.com/file/53QOyTQvFZW3e6YeevUzFg/Community-contributed-datasets?type=whiteboard&node-id=0%3A1&t=POCJh2I8350xeQLX-1)

### Solution or next step
Tagging @davidsmejia for next steps

**Comment by davidsmejia** [comment]
Closing as feature is on production
