### ISSUE TITLE
Write copy for README files

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/scpca-portal#49]
### Context

I will add a README file to downloads in https://github.com/AlexsLemonade/scpca-portal/issues/32

### Problem or idea

We want more info/copy in that than just a couple links.

### Solution or next step

I can handle getting the correct project link for each download, but I don't think I can write the copy for the rest of it.

**Comment by jaclyn-taroni** [comment]
Recording some decisions from today's discussion:

* Every download will have a README
* Project-specific READMEs will include links to `projects/<id>/` and the docs 
* Other ideas for content:
  * Introductory language
  * Brief example code
* The download for each sample in a project will contain the project-specific README

**Comment by jaclyn-taroni** [comment]
We probably want to include a link to our terms & conditions and if required, link to a page that includes any additional project specific terms.

**Comment by kurtwheeler** [comment]
This was closed by #93
