### ISSUE TITLE
Change modality field from string to list

### ISSUE THREAD

**Issue by arkid15r** [AlexsLemonade/scpca-portal#490]
*In another PR we should make this consistent.*

#### Change modality field from string to list.
Currently when we update counts on a project we concatenate modalities into a comma separated string. In order to facilitate introspection on a client we should make this an array type attribute and assign it as such.

_Originally posted by @davidsmejia in https://github.com/AlexsLemonade/scpca-portal/pull/481#pullrequestreview-1733019224_

**Comment by davidsmejia** [comment]
Closed with #494 and #491
