### ISSUE TITLE
Update contribution guideline text

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-portal#495]
### Context

From this discussion https://github.com/AlexsLemonade/ScPCA-admin/pull/728#discussion_r1415716312, we will want to update the contributing guidelines to give a different column name for submitter-provided cell ontology cell types:

> In https://github.com/AlexsLemonade/ScPCA-admin/pull/722 I updated this because CLO is the Cell Line Ontology whereas (confusingly) CL is the cell type ontology prefix. And I kind of want to encourage people to use the actual ids if they can.
> 
> But I guess we need to update https://scpca.alexslemonade.org/contribute#submitting-cell-metadata as well to match.

### Problem or idea

We want to change this column name from `CLO_term` to `CL_ontology_id` in https://github.com/AlexsLemonade/scpca-portal/blob/dev/client/src/config/contribution-guidelines.md

### Solution or next step

Change some text!

**Comment by jaclyn-taroni** [comment]
The text for those guidelines does not get changed directly in this repository. I'm closing this.
