### ISSUE TITLE
Loading Data Benchmarks

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/scpca-portal#501]
### Context

After the initial loading of a project with AnnData on staging the overall time to process a project has increased significantly. We do expect loading data to change significantly in the future. However, those changes are far out enough where it makes sense to investigate opportunities for improvement now.

### Problem or idea

I suggest that we break this up into two domains; transferring to and from s3 and generation of computed files.

#### Transferring to and from s3

We should explore using [boto3.s3.transfer](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/customizations/s3.html#boto3.s3.transfer.TransferConfig) instead of `aws s3 sync` for downloads and `boto3.s3.upload_file` for uploads. This seems more feature rich and has `use_threads` as well as other options worth investigating.

####  Generation of computed files

I don't have anything concrete for this part yet. 
In software we should review the code and ensure that there isn't any low hanging fruit.
Additionally, I think that it might be worth trying a `gp3` ebs volume. As we are currently using `gp2`.

### Solution or next step

In this issue:
- We should select a project with AnnData to be used as a benchmark.
- We should add the current benchmark time for processing that project.
- We should create separate issues for each attempt and run the benchmark project on staging and collect the times here.
 
Tagging @arkid15r for appropriate project selection and initial benchmark.

**Comment by arkid15r** [comment]
Some baseline numbers:

- SCPCP000001
  `time ./run_command.sh load_data --reload-all --scpca-project-id SCPCP000001`
  real    19m43.515s
  
  `time ./run_command.sh load_data --reload-all --scpca-project-id SCPCP000001 --no-cleanup-output-data --no-cleanup-input-data`
  real    7m42.803s

- SCPCP000005
  `time ./run_command.sh load_data --reload-all --scpca-project-id SCPCP000005`
  real    339m41.804s (339m3.846s on another run)

**Comment by arkid15r** [comment]
More results after code changes and server upgrade:

Full processing (all projects update)
```
for i in $(seq -f "%02g" 1 20); do
  time ./run_command.sh load_data --clean-up-input-data --clean-up-output-data --reload-existing --scpca-project-id SCPCP0000$i
done

```
Before the server upgrade: 3536m38.488s
After the server upgrade: 1488m28.101s

The bucket size is ~1200GB. That gives us an average total processing speed of ~48 GB/hour (vs. initial ~21 GB/hour).

The cost difference for the server upgrade:
  - gp2 to gp3 $14/mo -> $11.2/mo (cheaper!)
  - ec2 t2.small to t2.medium $23.36/mo -> $33.87/mo
  - total difference $37.36 -> $45.07 = +$7.71/mo
