### ISSUE TITLE
Update Portal description on scpca.alexslemonade.org

### ISSUE THREAD

**Issue by Jen-OMalley** [AlexsLemonade/scpca-portal#502]
### Context

This is part of updating the Portal and related copy to reflect that more than just tumor and xenograft samples will be available.

### Problem or idea

Replace this description (and related content) after a new description is drafted - `Database of uniformly processed single-cell data from pediatric cancer clinical samples and xenografts`

### Solution or next step

Replace description in the following place(s):

- [x] [scpca.alexslemonade.org homepage](https://scpca.alexslemonade.org/)

**Comment by Jen-OMalley** [comment]
New tagline - `Growing database of uniformly processed single-cell data from pediatric cancer tumors and model systems.`

**Comment by nozomione** [comment]
Merged #544 ✅
