### ISSUE TITLE
Changes to provide merged objects

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-portal#512]
### Context
This is dev hand-off ticket

### Problem or idea

The annotated changes for merged objects can be found [here](https://www.figma.com/file/qOpXrGXmufeRQ08Hu3m3yK/merged-objects?type=whiteboard&node-id=165%3A6183&t=cbXdm1Vue2F5wOum-1) 

### Solution or next step

Tagging @davidsmejia for next steps

**Comment by nozomione** [comment]
Merged PR #602, closing this issue.
