### ISSUE TITLE
Update About Page with new copy and illustrations

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-portal#520]
### Context

This is a dev hand-off ticket

### Problem or idea

The updated mockup for the About page and a link to the new copy can be found in this [figjam file](https://www.figma.com/file/EVZeubNFGSgfRQFr1yGXhs/scpca-about-page-redo?type=whiteboard&node-id=20%3A1326&t=EEb4sdKlUX77iZ6m-1)

I want to note that there are also separate illustrations for smaller screens (mobile). 

We want to do this at the same time as https://github.com/AlexsLemonade/scpca-portal/issues/485

### Solution or next step
Tagging @davidsmejia for next steps

**Comment by davidsmejia** [comment]
Closing in favor of #529  and #530
