### ISSUE TITLE
About Page Updates - Hero + Building the ScPCA Portal

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/scpca-portal#529]
### Context

We will be revamping the About Page and we should break up this up. So this issue is just for the Hero text change and updating the old "How it works" section and replacing it with the "Building the ScPCA Portal". This will include responsive layouts. These changes should not require any custom components.

### Problem or idea

The updated mockup for the About page and a link to the new copy can be found in this [figjam file](https://www.figma.com/file/EVZeubNFGSgfRQFr1yGXhs/scpca-about-page-redo?type=whiteboard&node-id=20%3A1326&t=EEb4sdKlUX77iZ6m-1)

**Note:  there are also separate illustrations for smaller screens (mobile).**

### Solution or next step
- Swap out the hero text
- Update Building the ScPCA Portal

**Comment by nozomione** [comment]
Merged #533
