### ISSUE TITLE
About Page Updates - Features and Enhancements + Support the Data Lab

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/scpca-portal#530]
### Context

We will be revamping the About Page and we should break up this up. 

This issue is just for the "Features and Enhancements" and "Support the Data Lab" sections. This should be a responsive implementation. These changes should not require any custom components.

### Problem or idea

The updated mockup for the About page and a link to the new copy can be found in this [figjam file](https://www.figma.com/file/EVZeubNFGSgfRQFr1yGXhs/scpca-about-page-redo?type=whiteboard&node-id=20%3A1326&t=EEb4sdKlUX77iZ6m-1)

### Solution or next step
- Update content in "Impact" section to the new "Features and Enhancements" section
- Add additonal copy and image to "Support the Data Lab" section.

**Comment by nozomione** [comment]
Merged #534
