### ISSUE TITLE
Use Django templates for README files generation

### ISSUE THREAD

**Issue by arkid15r** [AlexsLemonade/scpca-portal#556]
### Context

Related to https://github.com/AlexsLemonade/scpca-portal/issues/482 and https://github.com/AlexsLemonade/scpca-portal/issues/524

As the README files logic is getting more complex it makes sense to use a template engine for handling it.

### Problem or idea

Use Django template engine to render project README files (should be enough for our goal, no need for Jinja)

### Solution or next step

  - Update README templates with Django template language
  - Migrate data loading script
  - Add tests to make sure README files being generated properly

**Comment by davidsmejia** [comment]
closing with #569
