### ISSUE TITLE
Allow for sorting Sample Details table by download size

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-portal#557]
### Context
> [!note]
> Updated by @nozomione . Thank you for filing this @sjspielman!

Currently the download column of the samples table doesn't support sorting by file size and we want to add this functionality.

<details>
<summary><strong>Additional Context</strong></summary><br/>

While looking for a small-ish sample on the portal to work with, I found that sorting on Download Size in the "Sample Details" project tabs does not behave as expected, in that it does not sort.

Here's an example screen shot of attempting to sort for `SCPCP000009`. It's a bit all over the place.

<img src="https://github.com/AlexsLemonade/scpca-portal/assets/4701111/608c1912-15fe-4c85-97f3-63e131b9c05b" width=100px>

Some additional context, copied from @davidsmejia's reply when I brought this up in Slack:

> Yeah thats a good callout for a future feature. We can add this with/after AnnData due to relevant changes allowing for this.
> Sorting on download wasn't implemented until we had non-downloadable samples and we wanted them at the end of the table. Also because I didn’t think about that when I added and no one asked about it until now.
> The new samples table should allow for this because we filter on modality / format and each sample row will be representative of a single computed file which has a definitive size

</details>

### Problem or idea
We should make the `Download` column sortable by the file size in the samples table. 

### Solution or next step
Since the key we want to assign as an accessor,`size_in_bytes`, is in an array of objects (`computed_files`), we'll need to find a way to pass `computed_files[n].size_in_bytes` as the accessor of the `Download` column. 

React-table may not support for this type of case natively. My suggestion is to manipulate the samples table's data (i.e., `samples`) to only include a single computed file for each column before passing it to the `Table` component's  `data` prop. 

**Steps** (we can use existing methods and create a new one as needed):
1. Iterate `samples` and store `computed_files`  in a local state 
2. Iterate `computed_files` and use the `getFoundFile` method of `useDownloadOptionsContext` to get the computed file for each column
3. Add a new property (e.g., `computed_file`) to `samples` and assign the computed file obtained above (2) 
4. Define the accessor of the `Download` column to be `computed_file.size_in_bytes`  - I haven't tested it yet, but it should work (resource: [TanStack Repo: Nested data](https://github.com/TanStack/table/issues/579))
5. Pass the newly updated `samples` to  the `Table` component
6. Handle table data updates on states change (e.g., `modality`, `format`) using the local state (1).

Perhaps if there is no built-in React-table support, this is the easiest way to solve this problem. 

@davidsmejia Any suggestions, pleas share!

**Comment by davidsmejia** [comment]
Closing with #680
