### ISSUE TITLE
Privacy Policy Release Date Envar

### ISSUE THREAD

**Issue by nozomione** [AlexsLemonade/scpca-portal#562]
### Context

Currently, the content of the Privacy Policy page is pulled directly from the `md` file (`src/config/privacy-policy.md`). 

In order to better provide context as to when this `md` file was updated on the portal, we want to use env vars to display the updated date as "`Last Updated: YYYY-MM-DD`" at the bottom of the Privacy Policy page.

### Problem or idea
We should create new env vars  `STAGE_PRIVACY_POLICY_RELEASE` (for `staging`) and `PRIVACY_POLICY_RELEASE` (for `production`) to display the updated date on the Privacy Policy page. 

The date value should:
   -  match the date when the `md` file update was deployed to `production`.
   -  be generated locally in the format `YYYY-MM-DD` first and added to the env vars in Vercel.

### Solution or next step
- [x] Add the  `STAGE_PRIVACY_POLICY_RELEASE` and `PRIVACY_POLICY_RELEASE` to Vercel
- [x] Populate `process.env.PRIVACY_POLICY_RELEASE` in `next.config`
- [x] Display the date value at the bottom of the `/privacy-policy` page

**Comment by davidsmejia** [comment]
This looks good, can we change the name to `STAGE_PRIVACY_POLICY_RELEASE` etc. just for clarity.

**Comment by nozomione** [comment]
> This looks good, can we change the name to `STAGE_PRIVACY_POLICY_RELEASE` etc. just for clarity.

Done, thank you!

**Comment by nozomione** [comment]
Merged #567
