### ISSUE TITLE
Re-open call for contributions: Update contribution guidelines, add PDF, and remove card 

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-portal#575]
### Context

Since the last time we opened a call for contributions, we have altered the contributing guidelines that we track in `ScPCA-admin`. 

### Problem or idea

We need to port over the up-to-date guidelines, once a few issues I'll set as blocking are completed, and reverse the steps in #430

- [x] Update [the contributing guidelines](https://github.com/AlexsLemonade/scpca-portal/blob/dev/client/src/config/contribution-guidelines.md) to reflect the most recent changes.
- [x] Add a PDF version to `/src/public/`
- [x] Remove the card on `/contribute` that says we're not accepting contributions
- [x] Update config `contribute_hsform` to the form for contributing
- [x] Add back the contribution banner on the home page

### Solution or next step

I will complete the blocking items and then handoff to the Engineering team.

**Comment by davidsmejia** [comment]
Note: We are going to go with the new style of banner that renders above the navigation elements.
ex:
<img width="1707" alt="Screenshot 2024-03-26 at 10 42 34 AM" src="https://github.com/AlexsLemonade/scpca-portal/assets/1075609/4f704e52-6a74-492d-92f0-8411fe686673">

**Comment by nozomione** [comment]
Merged PRs #606, #607, #626.
