### ISSUE TITLE
 [AnnData Code Review] Fix the delay in updating `DownloadOptionsContext` state to resolve a bug in drop-down options in the `ProjectSamplesTable` component for `spatial`

### ISSUE THREAD

**Issue by nozomione** [AlexsLemonade/scpca-portal#598]
### Context

Reference Doc: [AnnData Requirements](https://data-lab-knowledge.slab.com/posts/ann-data-requirements-8fqdxqf7) 

There is a delay in updating the `DownloadOptionsContext` state which causes incorrect data format options to display in the `ProjectSamplesTable` component's drop-down for spatial.

#### Steps to reproduce the bug:
Please follow these steps to reproduce this bug.

**STEP 1** On `prod`, visit the project (e.g.,  `SCPCP000006` for spatial) page (https://scpca.alexslemonade.org/projects/SCPCP000006).

**STEP 2**  Select the "Samples Details" tab and click **Change** to open the download options modal.

![Screenshot 2024-03-19 at 1 50 43 PM](https://github.com/AlexsLemonade/scpca-portal/assets/31800566/73315177-95f4-41f0-9d06-6cd20ee522ec)

<br/> 

**STEP 3**  In the modal, toggle the "Modality" (`Single-cell`, `Spatial`) and "Data format" (`SingleCellExperiment(R)`, `AnnData(Python)`).

**STEP 4** There is a delay in displaying the correct data format options for each modality in the drop-down and `localStorage`.

For `Spatial`:

![Screenshot 2024-03-19 at 4 46 14 PM](https://github.com/AlexsLemonade/scpca-portal/assets/31800566/75de3747-64c0-459b-a0c0-f3e2ad064e6d)

For `Single-cell`:

![Screenshot 2024-03-19 at 4 43 42 PM](https://github.com/AlexsLemonade/scpca-portal/assets/31800566/e6b4c1cd-a768-411c-a327-a2ba6e1df855)

For `localStorage`:

![Screenshot 2024-03-19 at 4 34 05 PM](https://github.com/AlexsLemonade/scpca-portal/assets/31800566/8a40f671-3c3e-49b5-9668-2f75047ff497)

**NOTE:** Except for the following section, it correctly updates, and displays the available data format to users, even if they select the wrong data format for `Spatial` (i.e. `AnnData (Python)`) ✅:

![Screenshot 2024-03-19 at 1 57 06 PM](https://github.com/AlexsLemonade/scpca-portal/assets/31800566/5a8c2cd9-0c10-40b7-be2e-7973202a5c05)

### Problem or idea
To show users the correct available data formats for downloads, we should fix the error in updating the `DownloadOptionsContext` state.

### Solution or next step 
**Updated by** @nozomione: 
~~Please identify the cause of this delay to resolve the bug mentioned above.~~

My recommended solution is as follows:

**Step 1:** In `DownloadOptionsModal`, create a new state `selectedFormatOptions` that stores `format` available for each `modality`, and set the context state `formatOptions` as its initial value.

**Step 2:** Replace `formatOptions` with `selectedFormatOptions` as the value of `options` for the data format drop-down.

**Step 3:** Update `selectedFormatOptions` on `selectedModality` change. We can accomplish this by using the existing method `getOptionsAndDefault` in `useDownloadOptionsContext` and the `useEffect` hook.

**Step 4:** If the modal closes without saving, reset the values of `selectedFormat` and `selectedModality` to the corresponding user-saved preference (i.e. `userFormat` and `userModality` stored in localStorage) to make sure that the correct saved values are displayed in each drop-down to the user when the modal is reopened.

This solution fixes the errors that are mentioned in this issue!

**Comment by nozomione** [comment]
@davidsmejia I've added the recommended solution to the "solution or next step" section. Please let me know if you have any questions or comments!

**Comment by davidsmejia** [comment]
This proposed solution sounds good! Let's move forward with it.
