### ISSUE TITLE
Multiplexed libraries not available on portal

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-portal#599]
### Context

I was going to download the following project, which contains a number of multiplexed libraries, and it seems that most of those libraries are not available for download at the moment.

https://scpca.alexslemonade.org/projects/SCPCP000009

### Problem or idea

The only files that are available are those that have AnnData available, even for the ones that should have SCE files available. 

This seems to be related to a similar issue with spatial samples: https://alexslemonade.slack.com/archives/C023U61J16F/p1710440757078539

The data in the sample table in the download is also only for the available libraries, but this should probably include all libraries always?

Finally, in the table view for multiplexed samples, I would have expected all sampleIDs to be shown, not just the first? 

### Solution or next step

Tagging @davidsmejia, who may already be aware of these issues, but I could not find a matching issue.

**Comment by jashapiro** [comment]
So I think this is partly a misunderstanding by me of how things are on the portal: The multiplex libraries are there, but hidden as a modality so they are not downloaded as part of the main project downloads. Part of my confusion was that I was expecting the multiplexed samples to still appear in the `single_cell_metadata.tsv` file. I understand that future versions will not have a separate `_multiplexed.zip` file, which would prevent my confusion.

There remains some confusion from me in that the sample table on the website displays "Not Available for download" for some multiplexed samples, but "Not available in specified format" for others. If we do not want to have individual samples downloadable (which makes sense), then that text should probably somehow indicate that the data may be part of the project download?

**Comment by davidsmejia** [comment]
@jashapiro can we close this? With the latest production launch we now make the following available.
- Single-cell Single-cell Experiment project download with multiplexed samples included
- SIngle-cell Single-cell Experiment project download without mutliplexed samples included (Must tick checkbox to omit multiplexed samples)
- Single-cell AnnData project download without multiplexd samples. (Shows warning that Multiplexed samples are not available as AnnData
- Samples table shows all Single-cell Experiment samples as downloadable when `Single-cell` `Single-cell Experiment` are selected
- Samples table shows all AnnData samples as downloadable when `Single-cell` and `AnnData` are selected

All of the same files are available to download, its just more obvious what you are getting when you go to download something.

**Comment by jashapiro** [comment]
Not quite... I just downloaded the project data for `SCPCP000009_multiplexed`, and while it has all of the samples I would expect in the download, the `single_cell_metadata.tsv` file does not include `SCPCS000130`, `SCPCS000132`, `SCPCS000144`, and `SCPCS000158`. Basically it is missing the non-multiplexed samples in the project.

**Comment by jashapiro** [comment]
I guess that is really a slightly different issue than the one at the top, but related in a general way.

**Comment by davidsmejia** [comment]
From downloading without `omit multiplexed samples` checked gives me the following download
<img width="840" alt="Screenshot 2024-04-26 at 5 52 41 PM" src="https://github.com/AlexsLemonade/scpca-portal/assets/1075609/f7a01aaa-7849-4847-90ce-c0bc830d895f">

**Comment by davidsmejia** [comment]
Ok, we should be able to close this now that https://github.com/AlexsLemonade/scpca-portal/pull/687 is live.
