### ISSUE TITLE
[WIP] Remove `Multiplexed` from the modality options on portal

### ISSUE THREAD

**Issue by nozomione** [AlexsLemonade/scpca-portal#644]
### Context
`Multiplexed` will be removed from `modality` on both BE and FE codebase. On FE, the modality drop-down in the download options modal will no longer display `Multiplexed` as an option. 

The available downloads for the multiplexed libraries will be updated as follows: 

#### Project level:
|Modality|Format|Zip file|
|:--|:--|:--|
|`SINGLE_CELL`|`SingleCellExperiment (R)`|SCPCPXXXXXX_multiplexed.zip|

#### Sample level: 
|Modality|Format|Zip file|
|:--|:--|:--|
|`SINGLE_CELL`|`SingleCellExperiment (R)`|SCPCSXXXXXX.zip|
|`SINGLE_CELL`|`SingleCellExperiment (R)`|SCPCSXXXXXX_multiplexed.zip|
|`SINGLE_CELL`|`AnnData (Python)`|SCPCSXXXXXX_anndata.zip|

### Problem or idea
Based on the BE API update, the FE codebase should be adjusted to meet the above requirements.

### Solution or next step
This section will be filled out once the BE API changes are made.

> [!note]
> Please let me know if there are any details that need to be edited or added. Thank you @davidsmejia !

**Comment by davidsmejia** [comment]
Closed with #678
