### ISSUE TITLE
Write hdf5 files as h5ad for AnnData ComputedFiles

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/scpca-portal#650]
### Context

When compiling AnnData zips we want to start using the `.h5ad` file extension instead of the `.hdf5` that is currently on the portal. We are anticipating these file extensions changing on the input bucket in the future but in the mean time we just want to rename on the fly when we write the files to the ZipFile.

The contents of these files is unchanged.

### Problem or idea

I don't think there is much to do outside of replacing the extension before writing the file and updating tests to expect to see this new extension. I think that there will be some difficulty around the file mapping when we get to zipping a project but I am not 100% sure what that will look like at this time. It would be nice to implement this in a way that would work for either extension in the input bucket.

### Solution or next step

- Rename AnnData `.hdf5` files to `.h5ad` at time of ComputedFile creation
- Address project zip file mapping
- Fix tests to expect to see this new extension in AnnData zips

**Comment by jashapiro** [comment]
I think we can probably close or rewrite this: all hdf5 files in the `scpca-portal-staging-inputs` bucket have now been renamed as `.h5ad`: there should be no need for renaming, just making sure that the ingest scripts are looking for `.h5ad` files.

**Comment by davidsmejia** [comment]
Replaced with #667
