### ISSUE TITLE
Add data structure that describes state of test data

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/scpca-portal#668]
### Context

We now have versioned test data. One thing that would help clarity of the tests would be to group all of the expected test data output values into a data reusable data structure in the tests. This would allow for two things; fewer updates when updating the contents of the test data and reusable values for testing loading of the available test projects and samples.

### Problem or idea

We should create a data structure that contains constant values for comparing against the outputs of the load data command.

### Solution or next step

- Add test data values to a module or in the test_load_data test
- update tests to reference these values

**Comment by jaclyn-taroni** [comment]
Closing for now -- we probably need to do something _like this_ in the future, but will revisit as at a later date.
