### ISSUE TITLE
Simplify sorting of columns when writing metadata TSVs

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/scpca-portal#699]
### Context

While doing a code review I noticed that we have what seems to be some over complicated sorting preferences when writing output metadata files. This is specifically about ordering the columns and _not_ the rows. This _does not_ influence which columns are present in the output file, only the order in which we write them to the file header.

I am unsure how much of this is actually necessary and if we could simplify this by having a single sort order for all output metadata file columns independent of modality.

Currently we do the following:
- Pass a list of all `columns` that will be written to the output TSV into the `get_metadata_field_names` function.
- This function checks modality and sorts the provided `columns` based on the sort order for that modality.
- Any keys that were not present in the explicit modality sort order are moved to the end of `columns` in alphabetical order.
- The function then returns the same `columns` keys that were sorted.

The sort order for each modality can be found here:
https://github.com/AlexsLemonade/scpca-portal/blob/dev/api/scpca_portal/models/project.py#L770-L855

### Problem or idea

I suppose there are two questions that should be answered here:
- Does modality sufficiently affect the context in which the user would visually view the metadata files. I say visually because programmatically, order doesn't really mean that much.
- If the answer to the previous question is "no", can we create a single sort order that would influence the ordering of all metadata files independent of modality? That way we would always have `project_id`, `sample_id`, `library_id`, `disease` etc.

### Solution or next step

tagging: @dvenprasad @allyhawkins @jashapiro for input.

**Comment by allyhawkins** [comment]
@davidsmejia there are only a few things that are module specific, so I would agree that we could create a master list. I think the most important things for people to see first are the sample information, so I am proposing a new order that groups things with sample information, library information, project information, and then processing specific information. The processing metadata is the only thing that's modality specific. 

Another thing I noticed when looking at this list is that there are quite a few fields that we have in the metadata that aren't accounted for in the code that you sent. I took the current columns from the two metadata files that you had sent me recently that reflect the current contents of the portal. If we are going to set an order, we should incorporate all the columns that should be present. 

The one question I have is how this order reflects the samples table shown on the Portal? I remember we had quite a few conversations about that sample metadata order and wanted the order to be specific for users, so as long as changing the order in the actual file doesn't affect that table then I would update it. 

Here's a proposed order that I think would make sense: 

```
# use these categories for everything as the first columns in the metadata table 
# there is one column name that is specific to multiplexed in this list that is denoted 
Sample.Modalities.ALL: (
    # sample metadata 
    "scpca_sample_id",
    "scpca_library_id",
    "diagnosis",
    "subdiagnosis",
    "disease_timing",
    "age_at_diagnosis",
    "sex",
    "tissue_location",
    "participant_id",
    "submitter",
    "submitter_id",
    "organism",
    # library metadata
    "seq_unit",
    "technology",
    "total_reads",
    "mapped_reads",
    "sample_cell_count_estimate", 
    "sample_cell_estimates", # ONLY FOR MULTIPLEXED 
    "unfiltered_cells",
    "filtered_cell_count",
    "processed_cells",
    "has_cellhash",
    "includes_anndata",
    "is_cell_line",
    "is_multiplexed", 
    "is_xenograft",
    # project metadata
    "scpca_project_id",
    "pi_name",
    "project_title",
    # plus processing metadata that is modality specific 
) 
# then add in one of the following lists based on the modality 
processing.metadata.SINGLE_CELL: (
    # processing metadata
    "genome_assembly",
    "mapping_index",
    "alevin_fry_version", # REMOVE FOR SPATIAL
    "salmon_version", # REMOVE FOR SPATIAL
    "transcript_type", # REMOVE FOR SPATIAL
    "droplet_filtering_method", # REMOVE FOR SPATIAL
    "cell_filtering_method", # REMOVE FOR SPATIAL
    "prob_compromised_cutoff", # REMOVE FOR SPATIAL
    "min_gene_cutoff", # REMOVE FOR SPATIAL
    "normalization_method", # REMOVE FOR SPATIAL
    "date_processed",
    "workflow",
    "workflow_version",
    "workflow_commit",
)

processing.metadata.MULTIPLEXED: (
    # processing metadata
    "genome_assembly",
    "mapping_index",
    "alevin_fry_version", # REMOVE FOR SPATIAL
    "salmon_version", # REMOVE FOR SPATIAL
    "transcript_type", # REMOVE FOR SPATIAL
    "droplet_filtering_method", # REMOVE FOR SPATIAL
    "cell_filtering_method", # REMOVE FOR SPATIAL
    "prob_compromised_cutoff", # REMOVE FOR SPATIAL
    "min_gene_cutoff", # REMOVE FOR SPATIAL
    "normalization_method", # REMOVE FOR SPATIAL
    "demux_method", # ONLY FOR MULTIPLEXED 
    "date_processed",
    "workflow",
    "workflow_version",
    "workflow_commit",
)

processing.metadata.SPATIAL: (
    # processing metadata
    "genome_assembly",
    "mapping_index",
    "spaceranger_version", # FOR SPATIAL ONLY
    "date_processed",
    "workflow",
    "workflow_version",
    "workflow_commit",
)
```

**Comment by davidsmejia** [comment]
@allyhawkins 
- This order doesn't affect the portal / client side in any way, just how the columns in the downloaded file are ordered.
- If there are keys that aren't account for here then they are placed at the end of the file in alphabetical order

So before we get to this point we determine which keys are appropriate per modality and do things like rename "age" to "age_at_diagnosis" etc. Then when we go to write those dictionaries of library metadata combined with sample metadata to a TSV, we need to determine which order those fields are in. That's all this sorting order does, it doesn't determine which keys should be in the resulting file, only that if we see a key called "subdiagnosis" it should go after "diagnosis".

I like your proposed sort order based on sample, library, processing. Would like to hear if anyone has a problem with this.


The following unified list would be the same as having the process specific modalities.

```
sort_order = [
    # sample metadata 
    "scpca_sample_id",
    "scpca_library_id",
    "diagnosis",
    "subdiagnosis",
    "disease_timing",
    "age_at_diagnosis",
    "sex",
    "tissue_location",
    "participant_id",
    "submitter",
    "submitter_id",
    "organism",
    # library metadata
    "seq_unit",
    "technology",
    "total_reads",
    "mapped_reads",
    "sample_cell_count_estimate", 
    "sample_cell_estimates", # ONLY FOR MULTIPLEXED 
    "unfiltered_cells",
    "filtered_cell_count",
    "processed_cells",
    "has_cellhash",
    "includes_anndata",
    "is_cell_line",
    "is_multiplexed", 
    "is_xenograft",
    # project metadata
    "scpca_project_id",
    "pi_name",
    "project_title",
    # processing metadata
    "genome_assembly",
    "mapping_index",
    "spaceranger_version", # FOR SPATIAL ONLY
    "alevin_fry_version", # REMOVED FOR SPATIAL
    "salmon_version", # REMOVED FOR SPATIAL
    "transcript_type", # REMOVED FOR SPATIAL
    "droplet_filtering_method", # REMOVED FOR SPATIAL
    "cell_filtering_method", # REMOVED FOR SPATIAL
    "prob_compromised_cutoff", # REMOVED FOR SPATIAL
    "min_gene_cutoff", # REMOVED FOR SPATIAL
    "normalization_method", # REMOVED FOR SPATIAL
    "demux_method", # ONLY FOR MULTIPLEXED 
    "date_processed",
    "workflow",
    "workflow_version",
    "workflow_commit",
]

```

**Comment by allyhawkins** [comment]
> So before we get to this point we determine which keys are appropriate per modality and do things like rename "age" to "age_at_diagnosis" etc. Then when we go to write those dictionaries of library metadata combined with sample metadata to a TSV, we need to determine which order those fields are in. That's all this sorting order does, it doesn't determine which keys should be in the resulting file, only that if we see a key called "subdiagnosis" it should go after "diagnosis".

This makes sense to me! I think it would be nice to make sure that we specify an order for all columns that are going to be present in every library while we are doing this which is why I added them all to the list. Then the only thing that should be left is the additional metadata that is project specific, so that should bring more of a sense of consistent order to the sheets. I'm good with the combined version you have above.

**Comment by davidsmejia** [comment]
Agreed that explicitly ordering all keys is the right move.
I think the one item that would be missing would be the `scpca_project_id` which we do include currently for spatial downloads. Maybe we don't need this, but we should include it in the order for future use.

<img width="350" alt="Screenshot 2024-05-14 at 11 59 58 AM" src="https://github.com/AlexsLemonade/scpca-portal/assets/1075609/42fe1aac-1d7a-40bd-9164-818aadc358af">

**Comment by allyhawkins** [comment]
`scpca_project_id` is listed under `# project metadata`. We could move it to the front so that it's project ID, sample ID, and then library ID for all samples.

**Comment by jaclyn-taroni** [comment]
Where would the additional metadata that is project-specific go? At the end of the sample metadata? At the end (i.e., as the last columns after `workflow_commit`)?

**Comment by davidsmejia** [comment]
I talked to @jaclyn-taroni and we decided to stick additional metadata before library metadata. They will all be given the same sort priority so they will be grouped together.

**Comment by dvenprasad** [comment]
I think this ordering seems reasonable. 👍

**Comment by allyhawkins** [comment]
I was working on docs and noticed we forgot some columns that should be included. I am updating the order to reflect the change that project ID should be first and then added the new ontology columns. 

```
sort_order = [
    "scpca_project_id", 
    # sample metadata 
    "scpca_sample_id",
    "scpca_library_id",
    "diagnosis",
    "subdiagnosis",
    "disease_timing",
    "age_at_diagnosis",
    "sex",
    "tissue_location",
    "participant_id",
    "submitter",
    "submitter_id",
    "organism",
    # library metadata
    "seq_unit",
    "technology",
    "total_reads",
    "mapped_reads",
    "sample_cell_count_estimate", 
    "sample_cell_estimates", # ONLY FOR MULTIPLEXED 
    "unfiltered_cells",
    "filtered_cell_count",
    "processed_cells",
    "has_cellhash",
    "includes_anndata",
    "is_cell_line",
    "is_multiplexed", 
    "is_xenograft",
    # project metadata
    "scpca_project_id",
    "pi_name",
    "project_title",
    # processing metadata
    "genome_assembly",
    "mapping_index",
    "spaceranger_version", # FOR SPATIAL ONLY
    "alevin_fry_version", # REMOVED FOR SPATIAL
    "salmon_version", # REMOVED FOR SPATIAL
    "transcript_type", # REMOVED FOR SPATIAL
    "droplet_filtering_method", # REMOVED FOR SPATIAL
    "cell_filtering_method", # REMOVED FOR SPATIAL
    "prob_compromised_cutoff", # REMOVED FOR SPATIAL
    "min_gene_cutoff", # REMOVED FOR SPATIAL
    "normalization_method", # REMOVED FOR SPATIAL
    "demux_method", # ONLY FOR MULTIPLEXED 
    "date_processed",
    "workflow",
    "workflow_version",
    "workflow_commit",
]

```

**Comment by jashapiro** [comment]
> I was working on docs and noticed we forgot some columns that should be included. I am updating the order to reflect the change that project ID should be first and then added the new ontology columns.
> 


It looks like we are missing the `demux_samples` field for multiplexed data. I would add it after `technology` for multiplex samples only.

**Comment by davidsmejia** [comment]
Closing this with #730, #749

**Comment by davidsmejia** [comment]
actually closing now
