### ISSUE TITLE
Add util function for sorting columns of metadata TSVs

### ISSUE THREAD

**Issue by nozomione** [AlexsLemonade/scpca-portal#703]
### Context
Parent issue: #699 

Currently, we sort the columns of metadata TSV files during the write operations using `Project::get_metadata_field_names`. 

This method returns the sorted metadata field names for each TVS file based on the modality:

```py
  def get_metadata_field_names(self, columns, modality):
        """Returns a list of metadata field names based on the modality context."""
        ordering = {
            Sample.Modalities.MULTIPLEXED: (
                "scpca_sample_id",
               ...
```

To simply this logic, we want to make the column sorting modality-independent.

### Problem or idea
As detailed in the parent issue, we'll set a global sort order for all output metadata TSV files, regardless of their modality.

### Solution or next step
- Add the global sort order to the project settings in `common.py`
- Write a utility function `utils.get_sorted_field_names` that sorts the metadata keys and returns them as a list
- Make the following changes to `metadata_file.write_metadata_dicts`:
  - Use the new utility function to sort field names
  - Set `scpca_project_id`, `scpca_sample_id`, and `scpca_library_id` as the default sort order for rows
- Clean up the following code blocks in `Project` model: 
   - the variable `fieldnames` (which is passed to `metadata_file.write_metadata_dicts`)
   - the `get_metadata_field_names` method and the variable `key_set` (no longer required)
   - the logic for the vertical sort (for rows)

**Comment by davidsmejia** [comment]
This looks good, just wanted to point out the following:
- The tests do check for order so they will need to be updated.
- We will have one slight modification to the sort order as the global sort order wont be exhaustive as per the comments in #799. I think the solution for that should be to place an "*" in the global list after organisms and make that the default index for anything that is not specifically referenced in the list.
- If you do handle the sorting of rows (i think it is ok to do so in this PR) we will also want to clean up where we do that before sending it to `write_dicts_to_file` as it will be redundant.
