### ISSUE TITLE
Adding public attribute to ComputedFile model

### ISSUE THREAD

**Issue by avrohomgottlieb** [AlexsLemonade/scpca-portal#714]
### Context

In the `ComputedFile` model, `ComputedFile` objects are currently built by ways of a class method inside of `ComputedFile.get_(project/sample)_<modality>_file`, and then saved inside of `ComputedFile.process_computed_file`, right before their associated archives are uploaded to s3.

### Problem or idea

This behavior creates an ambiguity as to the goal of what `ComputedFile` objects are intending to represent. The confusion is as follows:
- If their goal is to represent a computed file which has been uploaded to s3 and is available for download, then `ComputedFile` objects should only be saved to the db after a successful upload. 
- If their goal is to represent the internal state of a computed file, with the goal of querying and aggregating computed file values as an intermediate step before uploading, then there's no reason to wait until right before uploading to save them.

### Solution or next step

A clarifying improvement to this design pattern would be to add another attribute to the `ComputedFile` model called `public`. This new attribute would satisfy both items of confusion detailed out above:
- It would allow for each `ComputedFile` object to be able to be saved for internal purposes right after being built (with `public=False`), satisfying the desire to maintain an internal state for `ComputedFile` objects.
- It would also allow for objects to be able to maintain a `public=True` state right after the computed file archive would be uploaded to s3, allowing for the available to query for computed files which are hosted on s3 and available for download.

**Comment by davidsmejia** [comment]
At this time it doesn't make sense to add a public computed file. Instead we should open an issue for indicating if a project has been "loaded" meaning the metadata is in the DB but not "packaged" meaning the computed file variants are available are on s3.
