### ISSUE TITLE
Metadata only download readme

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/scpca-portal#717]
### Context

We will be adding metadata only download to the portal. These downloadable zip's will have a readme and one metadata file that contains library metadata (combined with sample and project metadata per row).

Open questions:
- What changes need to happen to the docs?
- Do we need a `Usage` section?
- If someone downloads the portal-wide metadata do they still need to cite the individual projects that they use? Should we update the verbiage around that?

### Problem or idea

Below is an example of what I think the metadata file should look like.

> [!NOTE]
> We could use this file for both portal-wide metadata file as well as project specific metadata files if we conditionally render sections that depend on `project_accession`.

```markdown

Generated on: {{ date }}

# Alex's Lemonade Stand Foundation Single-cell Pediatric Cancer Atlas

The [Single-cell Pediatric Cancer Atlas](https://scpca.alexslemonade.org) is a database of single-cell and single-nuclei data from pediatric cancer clinical samples and xenografts, built by the [Childhood Cancer Data Lab](https://www.ccdatalab.org/) at [Alex's Lemonade Stand Foundation](https://www.alexslemonade.org/).

## Contents

{% if project_accession %}
This download includes associated metadata for samples from project [{{ project_accession }}]({{ project_url }}) in the ScPCA portal.
{% else %}
This download includes associated metadata for samples from all projects currently available at time of download in the ScPCA portal.
{% endif %}

See the [Downloadable files](https://scpca.readthedocs.io/en/stable/download_files.html) section in our documentation for more detailed information on files included in the download.

## Usage

<TBD>

## CHANGELOG

A summary of changes impacting downloads from the ScPCA Portal is available in [the CHANGELOG section of our documentation](https://scpca.readthedocs.io/en/stable/CHANGELOG.html).

## Contact

If you identify issues with this download, please [file an issue on GitHub.](https://github.com/AlexsLemonade/scpca-portal/issues/new) If you would prefer to report issues via e-mail, please contact us at [scpca@ccdatalab.org](mailto:scpca@ccdatalab.org).

## Citation

If you use these data in your research, you must cite:

- The data submitter using language provided as part of the project abstract (as applicable), the publication listed for the project (as applicable), or both.
- The ScPCA Portal using the language below.

For more information, please see [the How to Cite section of our documentation](https://scpca.readthedocs.io/en/stable/citation.html).

### Citing this project

{% for project_accession, project_url in included_projects %}

To cite data from {{ project_accession }}, please see the project abstract and publication information at [{{ project_accession }} page.]({{ project_url }})

{% endfor %}

### Citing the ScPCA Portal

When citing the ScPCA Portal, please cite the following preprint:

Hawkins A. G., J. A. Shapiro, S. J. Spielman, D. S. Mejia, D. V. Prasad, et al., 2024 The Single-cell Pediatric Cancer Atlas: Data portal and open-source tools for single-cell transcriptomics of pediatric tumors. _bioRxiv._ https://doi.org/10.1101/2024.04.19.590243

## Terms of Use

In using these data, you agree to our [Terms of Use](https://scpca.alexslemonade.org/terms-of-use).

{% if additional_terms %}
{{ additional_terms }}
{% endif %}

```

### Solution or next step

- Create the file with what is outlined in the above snippet to `api/scpca_portal/templates/readme/metadata_only.md`

Note: There is a departure from how we handle project accession as we now loop over tuples of (project_accession, project_url).

**Comment by allyhawkins** [comment]
> What changes need to happen to the docs?

We need to update the download section of the docs to include a section on downloading metadata. But I don't think that should change the link you have. 

> Do we need a Usage section?

I don't think so? I think how they use the metadata is really up to them. We just need to explain the contents of the metadata. 
It might be helpful to expand on the contents section and say this includes sample specific metadata (age, sex, diagnosis), library specific metadata (10x kit used, seq unit, etc), and processing metadata including package versions used for processing. 

> If someone downloads the portal-wide metadata do they still need to cite the individual projects that they use? Should we update the verbiage around that?

I think yes. If they use any data from any of the projects that project should be cited. I think you could update the project citation line to direct people to cite all projects that are used and to see the publication information for each project. You could then provide a link for each project available in the Portal or just remove the link all together.

**Comment by davidsmejia** [comment]
>  I think how they use the metadata is really up to them. We just need to explain the contents of the metadata.

For this I think we should add a section to the docs for unified metadata, not sure about naming. We could expand on the expected values here but it would be nice to not have to keep the docs and this README in sync.
Something like this: https://scpca.readthedocs.io/en/stable/download_files.html#metadata


>  I think you could update the project citation line to direct people to cite all projects that are used and to see the publication information for each project. You could then provide a link for each project available in the Portal or just remove the link all together.

Yes we can do this, we can iterate over each of the projects used to generate the file and put something there instead that says how to reference a project per line. Would we want to tell people how to identify the projects they are using? Or is it when they reference the portal-wide metadata they must cite all projects on the portal individually.

Something like this instead of what I had so we would handle a single project in the same way and just iterate over a list of 1 project.

```markdown

### Citing this project

{% for project_accession, project_url in included_projects %}

To cite data from {{ project_accession }}, please see the project abstract and publication information at [{{ project_accession }} page.]({{ project_url }})

{% endfor %}
```

**Comment by allyhawkins** [comment]
> For this I think we should add a section to the docs for unified metadata, not sure about naming. We could expand on the expected values here but it would be nice to not have to keep the docs and this README in sync.
Something like this: https://scpca.readthedocs.io/en/stable/download_files.html#metadata

Yes, I definitely agree that we would want a full version of the included metadata in the docs. You could then just link to that table or section of the docs in the `contents` section. 

> Yes we can do this, we can iterate over each of the projects used to generate the file and put something there instead that says how to reference a project per line. Would we want to tell people how to identify the projects they are using? Or is it when they reference the portal-wide metadata they must cite all projects on the portal individually.

I think it's more just about making sure if they use anything from a given project, they should cite that project. So if they download the project-wide metadata and then use information from a subset of projects, they know they need to cite each of those individually. But only for the projects that they actually use, not every single project. I think the edit you proposed of looping through all projects included in the download makes sense to me.

**Comment by dvenprasad** [comment]
The overall structure looks good to me!

**Comment by avrohomgottlieb** [comment]
Addressed in PR https://github.com/AlexsLemonade/scpca-portal/pull/744
