### ISSUE TITLE
Create DOWNLOAD_OPTIONS data structure and use it to query relevant libraries for computed file generation

### ISSUE THREAD

**Issue by avrohomgottlieb** [AlexsLemonade/scpca-portal#732]
### Context

When it comes to computing files, first `Sample::compute_sample_computed_files` is called, which archives together all of a sample's data and metadata files and then uploads the archive to s3. While files are being computed, `Sample::compute_sample_computed_files` also maintains a file mapping associating sample ids with its associated data file paths (which are available locally after being downloaded from s3 earlier on). This file mapping is then consumed by `Project::create_project_computed_files` when archiving its sample data and metadata files.

Issue https://github.com/AlexsLemonade/scpca-portal/issues/731 proposes an intended solution to remove the need for this file mappings data structure by saving all data file paths in an ArrayField on the `Library` model. With this solution, a `Project` (and its `Samples`) will have direct access to its desired data files necessary for archiving.

The way that files are archived at the `Project` and `Sample` level is by checking for different conditions inside of `Project|Sample::computed_project|sample_computed_files`, and then, based on these different checks, a `ComputedFile::get_project|sample_<modality>_file` subroutine is called which is responsible for the actual archiving.

### Problem or idea

The way that we proceed through `Project|Sample::computed_project|sample_computed_files` and check for a variety of different conditions has led to the following suboptimal design decisions:
- For the sake of code clarity, we currently have separate subroutines inside of `ComputedFile` which archive files, all of which share most of their code
- We are forced to explicitly check for all of the different download conditions, and only then call the correct `ComputedFile` subroutine, which contributes to code bloat and can be carried out more succinctly and programmatically

### Solution or next step

- Initialize a new data structure called `DOWNLOAD_OPTIONS` in a new file called `download_options.py` inside of the `config\` directory. This data structure will  include all possible permutations of computed file download options, organized as a list of dictionaries, each dictionary representing a valid configuration of download options.
- Write a new method on the `Library` model which takes a valid download options configuration with which to query the db and return all relevant libraries.
- Add a helper method to the `Library` model which translates a `data_file_path` (which is an s3 path) to a local file path of the data file which locates where it currently resides on disk. This translation helper method will no longer be necessary when we transition to lazy downloading.

**Comment by avrohomgottlieb** [comment]
Instead of putting DOWNLOAD_OPTIONS into `download_options.py`, let's put it at the bottom of `config/common.py`.

**Comment by davidsmejia** [comment]
just going to comment for posterity,

> Add a helper method to the Library model which translates a data_file_path (which is an s3 path) to a local file path of the data file which locates where it currently resides on disk. This translation helper method will no longer be necessary when we transition to lazy downloading.

The helper will probably exist but will be used to check if the file exists locally or needs to be re-downloaded

**Comment by avrohomgottlieb** [comment]
Addressed in PR https://github.com/AlexsLemonade/scpca-portal/pull/758
