### ISSUE TITLE
Add the metadata download on project level

### ISSUE THREAD

**Issue by nozomione** [AlexsLemonade/scpca-portal#736]
### Context
Design handoff: https://github.com/AlexsLemonade/scpca-portal/issues/701

On the portal, we are going to provide users with a metadata-only download option by adding buttons to the project card and the samples table. 

During the file download, the download modal UI should display metadata-only download content.

### Problem or idea
Based on the design, we'll implement metadata-only download buttons on projects and display metadata-only download content in the download modal.

### Solution or next step
- Create a new component for the download sample metadata button
- Add this new component to:
  -  `ProjectSearchResult`
  -  `ProjectSamplesTable`
- Render the metadata-only download content to `DownloadStarted`

**Comment by davidsmejia** [comment]
Looking at the Comps, I don't think we need to change to say `Sample` everywhere so let's only address appending `Metadata` to the title and leave the rest as it will render already.

Suggestion for next steps:

### Solution or next step
- Create new component `MetadataDownloadModal.js`
  - accepts the following props: `project`, `disabled`
  - wrap the existing `DownlodModal` component and provide the computed file for the computed file that matches on`metadata_only`
- `DownloadModal.js`
  - update to support checking for `metadata_only` to change the title
- `DownloadStarted.js
  - Check `metadata_only` on computed file to only show the metadata line.
- `Table.js`
  - Add prop `onFilterChange` defaults to noop
  - extract `globalFilter` renamed `currentFilter` where pageIndex is extracted
  - add useEffect that watches currentFilter and calls `onFilterChange`
- Add the download sample metadata button to:
  -  `ProjectSearchResult`
  -  `ProjectSamplesTable`
    - disabled when filter is not-empty (using new callback)

**Comment by davidsmejia** [comment]
Metadata only download is available on staging. Note that modality and format may be undefined which is something you might need to account for when rendering contents.

```
        {
            "created_at": "2024-06-11T13:57:23.470755Z",
            "format": null,
            "has_bulk_rna_seq": false,
            "has_cite_seq_data": false,
            "has_multiplexed_data": false,
            "id": 21011,
            "includes_merged": false,
            "metadata_only": true,
            "modality": null,
            "project": "SCPCP000001",
            "s3_bucket": "scpca-portal-deployer-staging",
            "s3_key": "SCPCP000001_all_metadata.zip",
            "sample": null,
            "size_in_bytes": 21528,
            "updated_at": "2024-06-11T13:57:23.470782Z",
            "workflow_version": "v0.8.0"
        },
```

**Comment by davidsmejia** [comment]
closed with 769
