### ISSUE TITLE
Implement updated version of Project::load_data in light of Library model

### ISSUE THREAD

**Issue by avrohomgottlieb** [AlexsLemonade/scpca-portal#743]
### Context

The new addition of the `Library` model allows us to dramatically consolidate the processes of parsing metadata and computing files inside of  `Project::load_data`. This new ability to save (and later query) all relevant metadata from the input metadata files via the `Sample` and `Library` model (including the locations of data file paths), enables us to move towards a more condensed and programmatic implementation of this behavior. 

Among areas that will be greatly affected includes:
- Consolidating metadata parsing to focus around saving `Sample` and `Library` objects, instead of creating various ad hoc data structures in memory which are currently passed through the different stages of the metadata parsing pipeline.
- Simplifying the process of combining the necessary `Sample` and `Library` metadata used in the output metadata file.
- Removing all dependencies on file mapping data structures held in memory and passed from `Sample` file computation to `Project` file computation.
- Removing the need to maintain workflow versions in memory between `Sample` and `Project` file computation.
- Releasing the order dependency that `Project` file computation must come after `Sample` file computation.
- Simplifying the way we compute files in a more dynamic and concise way via `DOWNLOAD_OPTIONS`, which we can more easily apply validation to later on.

These areas and others will benefit from this Epic.

**Comment by davidsmejia** [comment]
PRs associated with this EPIC will be targeting  `/feature/remove-file-mappings` - They will be merged into dev as a single PR.

**Comment by avrohomgottlieb** [comment]
Feature branch merged in in PR https://github.com/AlexsLemonade/scpca-portal/pull/801
