### ISSUE TITLE
Metadata files discussion

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/scpca-portal#748]
I was discussing the results of the new metadata files with @jashapiro and he made two points that I wanted to open up for discussion here.

Summarily:
- We have fields where values are not atomic and are written as Python Lists or Dicts. Is this how we want to handle this?
- We have blank cells that should probably be NA. Specifically `demux_samples`, `sample_cell_count_estimate`, `sample_cell_estimates`, and `demux_method` in the metadata file where some samples are multiplexed.

**Comment by jashapiro** [comment]
I just filed #751 and #750 about these, having not seen this come up while I was writing.

**Comment by davidsmejia** [comment]
Closing with #751 and #750
