### ISSUE TITLE
Output of multi-value fields

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-portal#750]
In the updated metadata files, fields with multiple values are being printed as python array/dict objects. 

For example, the `transcript_type` field often has the value `['total', 'spliced']`. It would be better to transform arrays like this into comma or semicolon-separated lists. i.e., this example would become `total,spliced` or `total;spliced`. (I slightly prefer the comma, but not at all strongly.)

Dictionaries show up in the `sample_cell_estimates` column, e.g., `{'SCPCS000131': 15, 'SCPCS000157': 815}`

These should probably be `SCPCS000131:15,SCPCS000157:815`, but I'll be honest that I don't love it. On the other hand I can't come up with a great solution here... One option would be to convert these to JSON, which at least would have a standard format for parsing.

**Comment by davidsmejia** [comment]
Closed with #786
