### ISSUE TITLE
Missing data in metadata files should be set as `NA`

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-portal#751]
For some fields the download files may have no value. For example, in multiplexed data, the `demux_method` has no value for non-multiplexed samples and the `sample_cell_count_estimate` and `sample_cell_estimates` fields are mutually exclusive. 

Currently these are exported with blank values, but those should be replaced with `NA` for consistency.

**Comment by allyhawkins** [comment]
This should also apply for projects with spatial samples. Things like `unfiltered_cells`, `has_cellhash`, `alevin_fry_version`, etc. are blank for the spatial libraries but not the regular single-cell libraries so we should populate those with NA.

**Comment by davidsmejia** [comment]
So assuming that all of these empty values are the difference in populated keys from one library_metadata.json to another then the solution should be as simple as adding an argument for `restval` when we go to write the metadata file.

Adding this line should fix the issue.
```python
kwargs["restval"] = kwargs.get("restval", common.NA)
```

This wouldn't overwrite any blank values from the input metadata files. If those are empty, then these would remain empty and we would need address that in a different way.

**Comment by davidsmejia** [comment]
Do we want common.NA to be "NA" or "N/A"?

**Comment by jashapiro** [comment]
"NA" is what we use elsewhere.
