### ISSUE TITLE
Samples table: Change 'Other Modalities' to 'Modalities'

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-portal#753]
### Context
During evals, users were confused by the `Other Modalities` field. They consistently assumed that the sample did not have single-cell data at all, but only dat the for the modalities mentioned in that column. 

### Problem or idea
Change the column to `Modalities` and display all the modalities available for the sample, including single-cell or single-nucleus.

### Solution or next step

Tagging @davidsmejia for next steps

**Comment by davidsmejia** [comment]
Requested changes:
- change sample column name from `Other Modalities` to `Modalities`
- manually prefix (put in front) `Single-cell` to all lists ONLY on the clientside sample table column that will now be called `Modality` - this probably means we can clean up any N/A handling as well.
