### ISSUE TITLE
Individual Report Recommendation: Include diagnosis, sample ID, and tissue location

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-portal#759]
### Context
During evals, people opened the reports first, and most times did not open the metadata file. But they had questions about it and also were trying to map the library to the sample.

### Problem or idea
We can include the sample ID, diagnosis, and tissue location in the reports. The idea is to include some of the sample level metadata so there is less hunting for the metadata. 

### Solution or next step

Tagging @allyhawkins or @jashapiro for any constraints and go/no go decison

**Comment by allyhawkins** [comment]
> We can include the sample ID, diagnosis, and tissue location in the reports. The idea is to include some of the sample level metadata so there is less hunting for the metadata.

I think this is a very reasonable request. I think we could easily include a table with sample metadata since all of that information is stored in the objects already.

**Comment by allyhawkins** [comment]
@dvenprasad I filed https://github.com/AlexsLemonade/scpca-nf/issues/765 to address this. We will add a sample metadata table to the main QC report.

**Comment by dvenprasad** [comment]
Could we also add to the cell type report? People will want to know where the tissue came from / diagnosis to discern cell type predictions (esp when the predictions are different)

**Comment by allyhawkins** [comment]
> Could we also add to the cell type report? People will want to know where the tissue came from / diagnosis to discern cell type predictions (esp when the predictions are different)

Yes, I added a note to the issue to add to the table to both reports.
