### ISSUE TITLE
Correct Name of Project Metadata Attribute - Submitter or Pi-Name

### ISSUE THREAD

**Issue by avrohomgottlieb** [AlexsLemonade/scpca-portal#763]
### Context

Inside of `METADATA_COLUMN_SORT_ORDER` in `common.py`, we have the metadata properties `submitter` and `submitter_id` listed under `Sample metadata` keys, while we have `pi_name` listed under `Project metadata` keys.

### Problem or idea

In `metadata_file.py`, while transforming metadata keys, we rename `submitter` to `pi_name` (located inside of `PROJECT_METADATA_KEYS`).

Which one do we want to use? As it currently stands, we're sending both keys through to the output `combined_metadata` file with identical values.

**Comment by davidsmejia** [comment]
Calling @allyhawkins for input

**Comment by allyhawkins** [comment]
I think I would keep `pi_name` and remove `submitter`, since that naming is more informative to users.

**Comment by avrohomgottlieb** [comment]
@allyhawkins  We can definitely do that. 

The global sort order that was okayed for metadata columns was as follows:
```
METADATA_COLUMN_SORT_ORDER = [
    "scpca_project_id",
    # Sample metadata
    "scpca_sample_id",
    "scpca_library_id",
    "diagnosis",
    "subdiagnosis",
    "disease_timing",
    "age_at_diagnosis",
    "sex",
    "tissue_location",
    "participant_id",
    "submitter",
    "submitter_id",
    ...
    # Library metadata
    ...
    # Project metadata
    "pi_name",
    "project_title",
    # Processing metadata
    ...
```

If we delete `submitter` and stick with `pi_name`, where should we put `pi_name` in the order here? It should probably be next to `submitter_id`, right? I guess the suggestions are:
- moving up `pi_name` into the location of `submitter` (in which case, should we keep `project_title` in its current location?)
- bringing down `submitter_id` to be next to `pi_name`
- something different

Thoughts?

**Comment by allyhawkins** [comment]
So `submitter_id` is actually sample specific, so we want to keep that where it is. I think you could just remove `submitter` altogether and keep `pi_name` where it is, next to `project_title`. That would keep things as sample, library, project metadata. Let me know if that is unclear!

**Comment by avrohomgottlieb** [comment]
Okay, then that's what we'll do. Makes perfect sense, thanks for being clear. Thanks Ally!

**Comment by avrohomgottlieb** [comment]
If it's okay with everyone, I'm actually going to reopen this issue and use it for any questions that might come up regarding metadata keys while I'm working on Issue https://github.com/AlexsLemonade/scpca-portal/issues/739

**Comment by avrohomgottlieb** [comment]
@allyhawkins I'm noticing that with Single-Cell libraries we currently pass through `processed_cells`, `filtered_cells` and `unfiltered_cells` to the output metadata tsv file, but with Spatial libraries we don't pass through `filtered_spots`, `unfiltered_spots` and `tissue spots`. Is this the desired behavior?

**Comment by allyhawkins** [comment]
> @allyhawkins I'm noticing that with Single-Cell libraries we currently pass through `processed_cells`, `filtered_cells` and `unfiltered_cells` to the output metadata tsv file, but with Spatial libraries we don't pass through `filtered_spots`, `unfiltered_spots` and `tissue spots`. Is this the desired behavior?

I think originally didn't include it in the list because we have not previously reported that in the `single_cell_metadata.tsv` file that is included with a spatial download. However, I don't see why we shouldn't include that information. I think you are correct that we should have `filtered_spots`, `unfiltered_spots`, and `tissue_spots` as metadata for spatial libraries and they should be included in the library metadata section of the metadata column order.

**Comment by avrohomgottlieb** [comment]
> If it's okay with everyone, I'm actually going to reopen this issue and use it for any questions that might come up regarding metadata keys while I'm working on Issue #739

Issue https://github.com/AlexsLemonade/scpca-portal/issues/739 closed, was addressed in PR https://github.com/AlexsLemonade/scpca-portal/pull/765
