### ISSUE TITLE
Convert List of multi-valued fields to a semicolon-delimited string

### ISSUE THREAD

**Issue by nozomione** [AlexsLemonade/scpca-portal#786]
### Context

Parent issue: #750

In the metadata files, multi-valued fields are currently output as Python lists that need to be converted to strings separated by semicolons.

e.g.) The `transcript_type` field is often outputted as `['total', 'spliced']`. We want to format this value as `"total;spliced"`.

### Problem or idea
We should convert the list of multi-valued fields to a semicolon-delimited string. 

### Solution or next step
I suggest the following solution:

1. Add a new utility method `utils.string_from_list` that transforms a list into a semicolon-delimited string:
```python
def string_from_list(value, delimiter=";"):
    return delimiter.join(value) if isinstance(value, list) else value
```
2. Add a new method `metadata_file.format_metadata_dict(metadata_dict)` that formats the given dictionary using `utils.string_from_list`
3. In `metadata_file.write_metadata_dicts`, use `for` loop and `metadata_file.format_metadata_dict` on ` sorted_list_of_dicts ` when writing each row.

**Comment by davidsmejia** [comment]
I think that we should do the following:
- write a util function that does the same as the above where we convert the list to the concatenated string
- add a new function `metadata_file.format_metadata_dict` that takes the single dict (row) and copies it, and mutates any list values by calling the new util method
- then change `metadata_file.write_metadata_dicts` to iterate over each item in the sorted list and calls `write_row` with the output of `format_metadata_dict`
