### ISSUE TITLE
remove `age_at_diagnosis` rename add `age_timing` to model

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/scpca-portal#796]
### Context

Currently we rename `age` to `age_at_diagnosis` when loading sample metadata. However, we will be receiving a new column that changes the meaning of this value and makes the renaming incorrect. The two new metadata keys for this information will be `age` and `age_timing`. `Age` should be the same and have the same meaning, but `age_timing` will indicate when that `age` was collected.

### Problem or idea

We need to update our models, serializers, and client to account for this change. Also, when we sort metadata keys to write them to file we use a common sort order that will need to be updated. Additionally, the there are many references to `age_at_diagnosis` in the tests that will need to be renamed.

These changes need to land with the corresponding client changes before deployment.

### Preflight
- [x] test data issue made
- [x] test data available
- [x] Where to place in sort order

### Solution or next step

- remove `age` / `age_at_diagnosis` rename from `metadata_file.SAMPLE_METADATA_KEYS` list to stop renaming
- add both / remove `age_at_diagnosis` from Sample model properties and makemigrations
- add both / remove `age_at_diagnosis` from all SampleSerializer
- add both / remove `age_at_diagnosis` from common.METADATA_COLUMN_SORT_ORDER
- update the tests to reflect `age` and `age_timing` and not `age_at_diagnosis`
- update `client/src/components/ProjectSamplesTable.js` to reflect this change

**Comment by avrohomgottlieb** [comment]
@davidsmejia we currently represent `age_at_diagnosis` (or `age` in this context) as a TextField in Postgres. Should it not be an Integer Field?

**Comment by avrohomgottlieb** [comment]
Addressed in PR https://github.com/AlexsLemonade/scpca-portal/pull/826
