### ISSUE TITLE
Provide a copy download link button on download modal

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-portal#867]
### Context

Due to the size of the downloads, some users prefer to directly download the data to a server/cluster. Currently there is no obvious way for them to get the download link. 

### Problem or idea

Add a copy download link button along with some context next to the download button.

### Solution or next step
Deepa is going to sketch out an initial draft and circulate it for async comments on slack.

**Comment by dvenprasad** [comment]
Hand-off Notes:
- `Copy Download Link` button only available for projects
- The (?) next to the button links to the FAQ to written by https://github.com/AlexsLemonade/scpca-docs/issues/345
- Once user clicks on `Copy Download Link`, it changes to `Copied to clipboard!`

Below are the screens:
- https://www.figma.com/design/AqRgSXil3E9bWihG2k1U3l/ScPCA-master?node-id=442-13019&t=7M8NSDsf6OurGFWe-4

![image](https://github.com/user-attachments/assets/cfe719c6-8cdd-4f07-a559-9839d995e812)


- https://www.figma.com/design/AqRgSXil3E9bWihG2k1U3l/ScPCA-master?node-id=1068-6023&t=7M8NSDsf6OurGFWe-4

![image](https://github.com/user-attachments/assets/19c21fdf-9a58-48ab-8f82-176c01779985)


@davidsmejia lmk if you need anything else from me.

**Comment by davidsmejia** [comment]
From meeting notes:
- We will move the agree to terms view to the front of the download modal flow.
- Change primary button text on terms view from “Download” to “Agree and Continue”
