### ISSUE TITLE
Closing call for contributions 10/16

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/scpca-portal#923]
### Context

We are closing the call for contributions on the ScPCA portal. Since this is something that we intend to reopen but do not have dates for we want to make this a configuration option based on an envar. This change needs to land on production before 10/16.

### Solution or next step

- add `CONTRIBUTION_OPEN` to envars / boolean like value (ON / OFF)
- add guidelines-closed.md to src from scpca-admin
- render closed version of guidelines when `CONTRIBUTION_OPEN` is `OFF`

**Comment by jaclyn-taroni** [comment]
On 10/16, not before.

**Comment by davidsmejia** [comment]
> On 10/16, not before.

Yeah, the switch needs to land on production prior, we will flip it on 10/16
